SOLR_PID_DIR=$HADATAC_SOLR/solr-5.2.1
SOLR_HOME=$HADATAC_SOLR/solr-home
LOG4J_PROPS=$HADATAC_SOLR/solr-5.2.1/server/resources/log4j.properties
SOLR_LOGS_DIR=$HADATAC_SOLR/solr-5.2.1/server/logs
SOLR_PORT=8983
