SOLR_PID_DIR=$HADATAC_SOLR/solr-6.5.0
SOLR_HOME=$HADATAC_SOLR/solr-home
LOG4J_PROPS=$HADATAC_SOLR/solr-6.5.0/server/resources/log4j.properties
SOLR_LOGS_DIR=$HADATAC_SOLR/solr-6.5.0/server/logs
SOLR_PORT=8983
